name: Run 1

on:
  schedule:
    - cron: "10 18 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t x1 .
      - run: docker run -d --name x1 x1
      - run: sleep 14400
      - run: docker stop x1
